import { ElevenLabsVoice } from '../types';

export const ELEVENLABS_DEFAULT_KEY = 'sk_da087fca72929f0f25e5591e8282d7c323175d67a51f8967';
export const DEFAULT_RANI_VOICE_ID = 'cgSgspJ2msm6clMCkdW9'; // Rani Ananya (Signature Hindi Companion)

/**
 * Curated exclusively with Hindi Female Voice Actors
 */
export const ELEVENLABS_VOICE_CATALOG: ElevenLabsVoice[] = [
  {
    id: 'cgSgspJ2msm6clMCkdW9',
    name: 'Rani (Ananya) - Sweet, Bubbly & Loving Hindi Voice (Default)',
    characterName: 'Rani (Ananya)',
    tagline: 'Signature Sweet & Bubbly Hindi Companion',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'expressive',
    useCase: 'conversational',
    descriptive: 'sweet, caring, bubbly, loving',
    description: 'Pyari aur madhur Hindi awaz. Rani ka signature character — sweet, playful, caring aur har baat me apnapan.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/cgSgspJ2msm6clMCkdW9/56a97bf8-b69b-448f-846c-c3a11dc83d76.mp3',
    avatarEmoji: '💖',
    personality: 'Pyari, caring, hamesha khush rehne wali aur har kaam me madadgar companion 💕',
    isRaniDefault: true,
  },
  {
    id: 'vghiSqG5ezdhd8F3tKAD',
    name: 'Saira - Young Hindi Influencer & Desi Creator',
    characterName: 'Saira',
    tagline: 'Energetic, Youthful Hindi Storyteller',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'professional',
    useCase: 'social_media',
    descriptive: 'casual, lively, relatable, energetic',
    description: 'Lively, modern Hindi female delivery with fast-paced youth charm, desi slang, and natural creator energy.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/514d94e9241c48e8b7905375729c436f/voices/vghiSqG5ezdhd8F3tKAD/FUiXiklM7yaALRuoP7yt.mp3',
    avatarEmoji: '✨',
    personality: 'Gen-Z desi influencer, mastikhor, fast replies aur chatpati baatein.',
  },
  {
    id: 'zMndFmtlJvAIQjxXWZTU',
    name: 'Shanaya - Respectful, Polite & Soothing Hindi Voice',
    characterName: 'Shanaya',
    tagline: 'Sweet, Polite & Empathetic Hindi Voice',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'professional',
    useCase: 'conversational',
    descriptive: 'respectful, polite, soothing, sweet',
    description: 'Bohot hi shisht, meethi aur soothing Hindi voice. Soft respectful tone jo har baat dhyan se sunti hai.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/ed9b05e6324c457685490352e9a1ec90/voices/zMndFmtlJvAIQjxXWZTU/0R2q5qqaoVtVZRE80J4I.mp3',
    avatarEmoji: '🌸',
    personality: 'Shishtachar, aadar, shaanti aur apnapan se baat karne wali dost.',
  },
  {
    id: 'EXAVITQu4vr4xnSDxMaL',
    name: 'Priya - Reassuring, Gentle & Caring Hindi Friend',
    characterName: 'Priya',
    tagline: 'Soft, Caring & Reassuring Hindi Voice',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'expressive',
    useCase: 'conversational',
    descriptive: 'gentle, caring, reassuring, soft',
    description: 'Soft aur gentle Hindi female voice jo dil ko sukoon de. Emotional support aur rozmarra ke kaamon ke liye best.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/EXAVITQu4vr4xnSDxMaL/0152fdf5-94f7-41e4-b040-97554e201b22.mp3',
    avatarEmoji: '🕊️',
    personality: 'Badi behen ya best friend jaisa sahara, calm aur positive guide.',
  },
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Kavya - Calm, Sweet & Meditative Hindi Voice',
    characterName: 'Kavya',
    tagline: 'Peaceful, Sweet & Balanced Tone',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'expressive',
    useCase: 'conversational',
    descriptive: 'calm, sweet, peaceful, pleasant',
    description: 'Shant aur madhur Hindi delivery. Stress kam karne aur dhyan lagane ke liye ekdum relaxing.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/21m00Tcm4TlvDq8ikWAM/b938e92e-99dd-4886-9a29-06aa4c85671c.mp3',
    avatarEmoji: '🌻',
    personality: 'Peaceful, thoughtful, dhyan se sunne wali aur hamesha sahaj rehne wali.',
  },
  {
    id: 'FGY2WhTYpPnrIDTdsKH5',
    name: 'Rhea - Cheerful, Quirky & Sassy Hindi Voice',
    characterName: 'Rhea',
    tagline: 'Upbeat, Sassy & Fun Hindi Voice',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'expressive',
    useCase: 'social_media',
    descriptive: 'sassy, quirky, cheerful, energetic',
    description: 'Bubbly, energetic aur funny Hindi delivery. Mazedaar jokes aur masti bhari baatcheet ke liye perfect.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/FGY2WhTYpPnrIDTdsKH5/67d4bf64-3404-406a-85d6-84df1c2d0f07.mp3',
    avatarEmoji: '⚡',
    personality: 'Masti bhari, funny jokes, bindass aur full of energy!',
  },
  {
    id: 'pFZP5JQG7iQjIQuC4Bku',
    name: 'Swara - Melodious, Poetic & Royal Hindi Voice',
    characterName: 'Swara',
    tagline: 'Melodious, Poetic & Traditional Hindi Tone',
    gender: 'female',
    age: 'middle_aged',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'professional',
    useCase: 'narrative_story',
    descriptive: 'melodious, poetic, elegant, rich',
    description: 'Shaandar Hindi shuddh uccharan, shayari aur kahani sunane ke liye behad madhur aur shandaar awaz.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/pFZP5JQG7iQjIQuC4Bku/89b68b35-b3dd-4348-a84a-a3c13a3c2b30.mp3',
    avatarEmoji: '👑',
    personality: 'Shayari, kavitayein aur shuddh Hindi bhasha ki pyari storyteller.',
  },
  {
    id: 'hpp4J3VqNfWAUOO0d1Us',
    name: 'Aarti - Professional, Clear & Educated Hindi Host',
    characterName: 'Aarti',
    tagline: 'Polished, Smart & Articulate Hindi Assistant',
    gender: 'female',
    age: 'middle_aged',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'professional',
    useCase: 'informative_educational',
    descriptive: 'polished, clear, smart, articulate',
    description: 'Spasht aur professional Hindi delivery jo study, business aur schedule planning ke liye adarsh hai.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/hpp4J3VqNfWAUOO0d1Us/dab0f5ba-3aa4-48a8-9fad-f138fea1126d.mp3',
    avatarEmoji: '🎓',
    personality: 'Smart, highly educated, spasht bolne wali professional assistant.',
  },
  {
    id: 'qSeXEcewz7tA0Q0qk9fH',
    name: 'Pooja - Warm, Empathetic & Caring Sister Voice',
    characterName: 'Pooja',
    tagline: 'Warm, Trustworthy & Supportive Hindi Voice',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'professional',
    useCase: 'conversational',
    descriptive: 'warm, trustworthy, empathetic, supportive',
    description: 'Ghar jaisi apnapan bhari Hindi awaz. Rozmarra ki baatcheet me hamesha saath dene wali.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/database/workspace/228d4047a7e64c3ca68131d246d93ef2/voices/qSeXEcewz7tA0Q0qk9fH/zDds5EkXR72GXolhj81V.mp3',
    avatarEmoji: '🌟',
    personality: 'Bharosemand, sahanubhuti purna aur hamesha madad ke liye tatpar.',
  },
  {
    id: '9BWtsMINqrJLrRacOk9x',
    name: 'Neha - Dynamic, Modern & Expressive Hindi Anchor',
    characterName: 'Neha',
    tagline: 'Dynamic, High-Energy Hindi Dialogue Voice',
    gender: 'female',
    age: 'young',
    accent: 'indian',
    language: 'Hindi / Hinglish (हिंदी / हिंग्लिश)',
    category: 'expressive',
    useCase: 'social_media',
    descriptive: 'expressive, dynamic, bright, modern',
    description: 'High dynamic emotional range wali modern Hindi voice. News, entertainment aur reminders ke liye energetic.',
    previewUrl: 'https://storage.googleapis.com/eleven-public-prod/premade/voices/9BWtsMINqrJLrRacOk9x/40707c9e-52ec-4763-ba92-d04b3cf4a4bc.mp3',
    avatarEmoji: '🎭',
    personality: 'Radio jockey / podcast host vibe — har baat me excitement aur energy!',
  },
];
